version: "3"

services:
  mysql:
    image: mysql:5.6
    command: mysqld --max-connections=1000 --max-allowed-packet=128M --innodb-log-file-size=256M --lower-case-table-names=1
    ports:
      - 3307:3306
    networks:
      - vmax
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql-db-1:/var/lib/mysql

  mongodb:
    image: mongo:3.2
    command: mongod --noprealloc --smallfiles --logpath=/dev/null # --quiet
    ports:
      - 27018:27017
    networks:
      - vmax
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_DATABASE=admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-db:/data/db

  seon-master-api:
      image: 245255707803.dkr.ecr.us-east-1.amazonaws.com/seon-master-api:develop
      ports:
        - 8088:80
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ConnectionStrings:SeonMaster=server=mysql;uid=root;pwd=password;database=seonmaster;port=3306;
      networks:
        - vmax
      deploy:
        replicas: 1

networks:
  vmax:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
volumes:
  mysql-db-1:
  mongo-db:
